[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=100000'''

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

